/*
* generated by Xtext
*/
package org;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class LetaUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.ui.internal.LetaActivator.getInstance().getInjector("org.Leta");
	}
	
}
