/*
 * generated by Xtext
 */
package org.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LetaUiModule extends org.ui.AbstractLetaUiModule {
	public LetaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
