/*
 * generated by Xtext
 */
package org.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LetaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.ui.internal.LetaActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.ui.internal.LetaActivator.getInstance().getInjector("org.Leta");
	}
	
}
