/*
* generated by Xtext
*/
package org.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.services.LetaGrammarAccess;

public class LetaParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private LetaGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.parser.antlr.internal.InternalLetaParser createParser(XtextTokenStream stream) {
		return new org.parser.antlr.internal.InternalLetaParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Leta";
	}
	
	public LetaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(LetaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
