/*
 * generated by Xtext
 */
package org;

import org.eclipse.xtext.parser.antlr.ISyntaxErrorMessageProvider;

import com.google.inject.Binder;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class LetaRuntimeModule extends org.AbstractLetaRuntimeModule {

    @Override
    public void configure(Binder binder) {
	super.configure(binder);
	
	binder.bind(ISyntaxErrorMessageProvider.class).to(LetaSyntaxErrorMessageProvider.class);
    }

}
